services:

  mongo-db:
    image: mongo:6.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo-db
    environment:
      - PORT=3000
      - MONGO_USER=mongo_user
      - MONGO_PASS=123456
      - MONGO_URL=mongodb://mongo_user:123456@mongo-db:27017/admin
      - MONGO_DB_NAME=mystore
      - JWT_SEED=12345
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules